### PR TITLE
Koa 2

### PR DESCRIPTION
**Pull request by yf-hk**

### CODE REVIEW

**Comment by octatone** [comment]
This repo hasn't been updated for 2 years. @dayAlone would you consider transferring ownership so we can move forward with the current releases of Koa?

**Comment by dayAlone** [comment]
@octatone Hello, no problem, do you want to be the owner?

**Comment by octatone** [comment]
Sure. Thanks!

**Comment by octatone** [comment]
Could you add me as a collaborator on npm to publish a new version? my username there is raymondmayjr

**Pull request merged**
